name: My-first-actions-workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
          
        - name: welcome msg
          run: echo "Hello, Good Morning! and how are yo"

        - name: reading files on this repo and giving 
          run: ls -la

        - name: reading app.py file
          run: cat app.py